# -*- coding: utf-8 -*-
"""
SMU Modular Handler Component
自動解耦之專屬業務處理模組
"""
import os
import sys
import re
import json
import time
import shutil
import urllib.request
import urllib.parse
import subprocess
import threading
from pathlib import Path
from typing import Dict, Any, List, Optional
import concurrent.futures

from managers import config_manager
from managers import steam_manager
from managers import unified_manifest_manager

class InstallHandler:
    def fetch_manifest(self, appid: str) -> Dict[str, Any]:
        """
        透過 UnifiedManifestManager 與多層自癒引擎取得入庫清單：
        1. 優先線上 Ryuu / Lua.tools 聚合查詢（支援智慧重試）
        2. 次選 SteamDB 官方資料庫歷史 Depot 提取
        3. 備選 Google Drive 網盤補丁庫之專屬 Lua 腳本
        4. 備選 本地 Steam/config/lua 既有設定檔
        5. 兜底 基礎入庫腳本 (addappid)
        """
        appid_str = str(appid).strip()
        sp = self._steam_path or steam_manager.find_steam_path()

        # 1. 嘗試線上多源聚合查詢 (給予 8 秒連線並支援重試)
        search_res = {}
        depots = {}
        best_source = "ryuu"
        try:
            search_res = self._unified_mgr.search_all_sources(appid_str, timeout=8)
            depots = search_res.get("ryuu", {}).get("depots", {})
            best_source = search_res.get("best_source", "ryuu")

            # 若初次查詢未取得 depots，進行一次重試
            if not depots:
                time.sleep(0.5)
                search_res = self._unified_mgr.search_all_sources(appid_str, timeout=10)
                depots = search_res.get("ryuu", {}).get("depots", {})
                best_source = search_res.get("best_source", "ryuu")
        except Exception as e:
            print(f"[fetch_manifest] AppID {appid_str} 線上多源查詢異常: {e}")

        # 2. 若線上清單為空，嘗試從 SteamDB 資料庫提取 Depots
        if not depots:
            try:
                from managers import version_resolver
                sdb_info = version_resolver.fetch_steamdb_manifests(appid_str, timeout=6)
                sdb_manifests = sdb_info.get("manifests", {})
                if sdb_manifests:
                    depots = sdb_manifests
                    best_source = "steamdb"
            except Exception as e:
                print(f"[fetch_manifest] AppID {appid_str} SteamDB 提取異常: {e}")

        # 3. 若有 Depots 清單，自動組裝含 Key 之完整 Lua
        if depots:
            keys_cache = self._unified_mgr.get_cached_depot_keys() or {}
            lua_lines = [
                f"-- {appid_str} - Auto Generated by UnifiedManifestManager ({best_source.upper()})",
                f"addappid({appid_str})"
            ]
            has_any_key = False
            for did, gid in depots.items():
                did_str = str(did).strip()
                key = keys_cache.get(did_str)
                if key and len(key) == 64:
                    lua_lines.append(f'addappid({did_str}, 0, "{key}")')
                    has_any_key = True
                else:
                    lua_lines.append(f"addappid({did_str})")
                if gid:
                    lua_lines.append(f'setManifestid({did_str}, "{gid}")')

            assembled_lua = "\n".join(lua_lines) + "\n"
            return {
                "lua": assembled_lua,
                "source": best_source.upper(),
                "has_key": has_any_key,
                "manifest_count": len(depots),
                "depots": depots,
                "search_result": search_res
            }

        # 4. 備援檢查：Google Drive 網盤補丁庫是否收錄專屬 Lua 或補丁
        try:
            from managers import onlinefix_manager
            ps = onlinefix_manager.get_patch_sources(target_app_id=appid_str, allow_network=False)
            app_src = ps.get(appid_str, {})

            # 若本地或網盤有已下載的 Lua 內容
            if sp:
                local_lua = Path(sp) / "config" / "lua" / f"{appid_str}.lua"
                if local_lua.exists() and local_lua.stat().st_size > 20:
                    content = local_lua.read_text(encoding='utf-8', errors='ignore')
                    return {
                        "lua": content,
                        "source": "LOCAL_CACHE",
                        "has_key": False,
                        "manifest_count": 1,
                        "depots": {},
                        "search_result": {}
                    }

            if app_src.get("cloud_rar") or app_src.get("cloud_lua"):
                # 該遊戲存在聯機補丁/解鎖檔，生成標準入庫腳本
                basic_lua = f"-- {appid_str} - Auto Generated Basic Unlocker (Cloud Patch Supported)\naddappid({appid_str})\n"
                return {
                    "lua": basic_lua,
                    "source": "GDRIVE_PATCH",
                    "has_key": False,
                    "manifest_count": 0,
                    "depots": {},
                    "search_result": {}
                }
        except Exception as e:
            print(f"[fetch_manifest] AppID {appid_str} 網盤備援檢查異常: {e}")

        # 5. 若本地已有設定檔，讀取使用
        if sp:
            local_lua = Path(sp) / "config" / "lua" / f"{appid_str}.lua"
            if local_lua.exists() and local_lua.stat().st_size > 10:
                content = local_lua.read_text(encoding='utf-8', errors='ignore')
                return {
                    "lua": content,
                    "source": "LOCAL_FALLBACK",
                    "has_key": False,
                    "manifest_count": 1,
                    "depots": {},
                    "search_result": {}
                }

        # 6. 最終兜底：生成基礎 addappid 入庫腳本
        fallback_lua = f"-- {appid_str} - Auto Generated Safe Fallback\naddappid({appid_str})\n"
        return {
            "lua": fallback_lua,
            "source": "FALLBACK",
            "has_key": False,
            "manifest_count": 0,
            "depots": {},
            "search_result": {}
        }

    def write_lua(self, appid: str, lua_content: str, source: str = "", dlcs: list = None) -> Dict[str, Any]:
        """將 Lua 腳本寫入 Steam/config/lua/{appid}.lua 並設定唯讀保護"""
        sp = self._steam_path or steam_manager.find_steam_path()
        if not sp: return {"ok": False, "msg": "找不到 Steam 路徑"}
        lua_dir = Path(sp) / "config" / "lua"
        lua_dir.mkdir(parents=True, exist_ok=True)
        lua_file = lua_dir / f"{appid}.lua"

        try:
            import stat
            if lua_file.exists():
                os.chmod(lua_file, stat.S_IWRITE | stat.S_IREAD)
            with open(lua_file, "w", encoding="utf-8") as f:
                f.write(lua_content)
            os.chmod(lua_file, stat.S_IREAD)
            # 即時動態注入 VDF：為新入庫遊戲預先關閉 Steam 官方雲端開關
            try:
                from managers.steam_cloud_helper import disable_official_cloud_for_single_appid
                disable_official_cloud_for_single_appid(Path(sp), str(appid))
            except Exception as _ce:
                print(f"[WebApi] 即時關閉新入庫遊戲官方雲端失敗: {_ce}")

            return {"ok": True}
        except Exception as e:
            return {"ok": False, "msg": str(e)}

    def check_local_lua_exists(self, appid: str) -> Dict[str, Any]:
        """檢查 Steam/config/lua/{appid}.lua 是否存在且內容有效"""
        sp = self._steam_path or steam_manager.find_steam_path()
        if not sp: return {"exists": False}
        lua_f = Path(sp) / "config" / "lua" / f"{appid}.lua"
        return {"exists": bool(lua_f.exists() and lua_f.stat().st_size > 20)}

    def auto_stock_after_import(self, appid: str, game_name: str = "") -> Dict[str, Any]:
        """
        入庫後自動執行「多源最佳清單部署 + ACF 防 401 赦免 + 鎖定」
        支援 SteamDB 官方對齊、智能多源重試與快取即時更新。
        自動生成全鏈路結構化 Manifest 診斷 Log 報告。
        """
        from managers.manifest_logger import ManifestUpdateLogger
        appid_str = str(appid).strip()

        # 嘗試解析遊戲名稱供日誌報告展示
        if not game_name:
            try:
                cache_file = Path(__file__).parent.parent / "data" / "game_cache.json"
                if cache_file.exists():
                    gc = json.loads(cache_file.read_text(encoding="utf-8"))
                    game_name = gc.get(appid_str, {}).get("name", "")
            except Exception:
                pass

        try:
            logger = ManifestUpdateLogger(appid_str, game_name=game_name or f"App_{appid_str}")
            logger.log_step("啟動更新", f"收到 AppID {appid_str} 之 Manifest 更新請求")

            if not appid_str or not appid_str.isdigit():
                logger.log_error("參數校驗", f"無效或未提供 AppID: '{appid}'")
                log_res = logger.finish(False, f"無效或未提供 AppID: '{appid}'")
                return {
                    "ok": False,
                    "complete": False,
                    "msg": f"無效或未提供 AppID: '{appid}'",
                    "log_path": log_res.get("log_path"),
                    "log_filename": log_res.get("log_filename"),
                    "report_markdown": log_res.get("report_markdown")
                }

            from managers import version_resolver

            # 1. 取得 SteamDB 最新 Manifest 資訊作為最高仲裁基準
            logger.log_step("SteamDB檢測", f"查詢 SteamDB 最新官方 Manifest 基準: {appid_str}")
            sdb_info = version_resolver.fetch_steamdb_manifests(appid_str, timeout=4)
            sdb_manifests = sdb_info.get("manifests", {})
            logger.log_step("SteamDB結果", f"SteamDB 包含 {len(sdb_manifests)} 個 Depot 官方基準清單")

            # 2. 進行多源搜尋仲裁（傳入 sdb_manifests）
            logger.log_step("多源仲裁", "比對 Ryuu 與 Lua.tools 可用來源...")
            search_res = self._unified_mgr.search_all_sources(appid_str, timeout=8, steamdb_manifests=sdb_manifests)

            # 若初次未找到可用源，自動重試一次
            if search_res.get("best_source") == "none":
                logger.log_step("多源仲裁", "初次搜尋無可用源，延長逾時重試...", status="WARN")
                search_res = self._unified_mgr.search_all_sources(appid_str, timeout=10, steamdb_manifests=sdb_manifests)

            logger.log_step("仲裁結果", f"最佳來源: {search_res.get('best_source')}，仲裁依據: {search_res.get('best_reason')}")

            # 3. 執行部署 (支援進度即時回呼至前端 UI，若 Ryuu 失敗即刻顯示備援切換)
            def on_progress(p_text: str):
                if getattr(self, "_window", None):
                    try:
                        self._window.evaluate_js(f"window.onManifestProgress && window.onManifestProgress({json.dumps(appid_str)}, {json.dumps(p_text)});")
                    except Exception:
                        pass

            ok, msg = self._unified_mgr.deploy_best_manifest(appid_str, search_res, progress_cb=on_progress, logger=logger)

            # 🌟 核心同步：確定完成更新後，立即將該遊戲更新狀態移出待更新名單，同步寫入快取
            if ok:
                updates_file = Path(__file__).parent.parent / "data" / "manifest_updates.json"
                try:
                    from datetime import datetime
                    updates = {}
                    if updates_file.exists():
                        updates = json.loads(updates_file.read_text(encoding="utf-8"))
                    updates[appid_str] = {
                        "appid": appid_str,
                        "has_update": False,
                        "version_status": "最新版",
                        "latest_date": datetime.now().strftime("%Y-%m-%d"),
                        "best_source": search_res.get("best_source", "ryuu")
                    }
                    updates_file.write_text(json.dumps(updates, ensure_ascii=False, indent=2), encoding="utf-8")
                except Exception:
                    pass

            log_res = logger.finish(ok, msg)

            self.invalidate_games_cache()
            return {
                "ok": ok,
                "complete": ok,
                "msg": msg,
                "log_path": log_res.get("log_path"),
                "log_filename": log_res.get("log_filename"),
                "report_markdown": log_res.get("report_markdown")
            }
        except Exception as e:
            logger.log_error("更新未預期異常", str(e), exc=e)
            log_res = logger.finish(False, f"更新 Manifest 發生異常: {e}")
            return {
                "ok": False,
                "complete": False,
                "msg": f"更新 Manifest 發生異常: {e}",
                "log_path": log_res.get("log_path"),
                "log_filename": log_res.get("log_filename"),
                "report_markdown": log_res.get("report_markdown")
            }

    def get_latest_manifest_log(self) -> Dict[str, Any]:
        """取得最後一次更新之全鏈路診斷 Log 報告"""
        from managers import manifest_logger
        return manifest_logger.get_latest_log()

    def open_manifest_log_file(self, log_path: str = "") -> Dict[str, Any]:
        """使用系統預設文字編輯器 (如記事本) 開啟指定更新日誌"""
        from managers import manifest_logger
        p = Path(log_path) if log_path else Path(manifest_logger.get_logs_directory()) / "latest_update.log"
        if not p.exists():
            return {"ok": False, "msg": f"找不到日誌檔案: {p}"}
        try:
            os.startfile(str(p))
            return {"ok": True, "path": str(p)}
        except Exception as e:
            return {"ok": False, "msg": str(e)}

    def start_batch_update_session(self, target_games: List[Dict[str, Any]]) -> str:
        """啟動批次更新調度記錄"""
        from managers import batch_logger
        return batch_logger.start_session(target_games)

    def log_batch_update_item(self, session_id: str, appid: str, name: str, success: bool, duration_ms: int = 0, msg: str = ""):
        """記錄單一遊戲批次更新結果"""
        from managers import batch_logger
        batch_logger.log_session_item(session_id, appid, name, success, duration_ms=duration_ms, msg=msg)

    def finish_batch_update_session(self, session_id: str, summary: str = "") -> Dict[str, Any]:
        """結算並落盤批次更新總診斷報告"""
        from managers import batch_logger
        return batch_logger.finish_session(session_id, summary=summary)

    def open_manifest_logs_dir(self) -> Dict[str, Any]:
        """在 Windows 檔案總管中開啟診斷日誌資料夾"""
        from managers import manifest_logger
        d = Path(manifest_logger.get_logs_directory())
        d.mkdir(parents=True, exist_ok=True)
        try:
            os.startfile(str(d))
            return {"ok": True, "path": str(d)}
        except Exception as e:
            return {"ok": False, "msg": str(e)}

    def get_onlinefix_appids(self) -> List[str]:
        """取得所有在網盤中收錄有 Online-Fix / ZeiGames 聯機補丁的遊戲 AppID 列表"""
        from managers import onlinefix_manager
        try:
            return onlinefix_manager.get_all_onlinefix_appids()
        except Exception:
            return []

    def get_steam_download_report(self, appid: str) -> Dict[str, Any]:
        """即時查詢 Steam 下載狀態回報與錯誤碼"""
        from managers import onlinefix_manager
        appid_str = str(appid).strip()
        rep = onlinefix_manager.get_steam_app_download_report(appid_str)
        rep["is_watching"] = onlinefix_manager._deploy_watcher.is_watching(appid_str)
        return {"ok": True, "report": rep}

    def launch_steam_install(self, appid: str, game_name: str = "") -> Dict[str, Any]:
        """喚起 Steam 開始下載/安裝遊戲主程式，並自動啟動下載狀態監控"""
        from managers import steam_manager
        try:
            appid_str = str(appid).strip()
            sp = self._steam_path or steam_manager.find_steam_path()
            # 🌟 關鍵修復：喚起 Steam 下載前必須先解除唯讀鎖定，確保 Steam 有權限讀寫 depotcache 與 ACF
            if sp:
                steam_manager.unlock_game_version(appid_str, sp)
                # 若 ACF 有殘留的 UpdateResult 錯誤碼，自動重設為 0
                acf = steam_manager.find_appmanifest(appid_str, sp)
                if acf and acf.exists():
                    try:
                        c = acf.read_text(encoding="utf-8", errors="ignore")
                        if re.search(r'"UpdateResult"\s+"[^0"]+"', c):
                            c = re.sub(r'"UpdateResult"\s+"[^"]*"', '"UpdateResult"\t\t"0"', c)
                            acf.write_text(c, encoding="utf-8")
                    except Exception:
                        pass

            os.startfile(f"steam://install/{appid_str}")

            # 自動啟動背景監控：若正常下載完成則自動部署補丁；若報錯或取消則中斷部署
            self.start_steam_install_watcher(appid_str, game_name)
            return {"ok": True, "msg": f"已喚起 Steam 開始安裝遊戲 (AppID: {appid_str})，正在背景自動監控下載進度…"}
        except Exception as e:
            return {"ok": False, "msg": f"喚起 Steam 安裝失敗: {e}"}

    def start_steam_install_watcher(self, appid: str, game_name: str = "") -> Dict[str, Any]:
        """啟動 Steam 下載監控，等待下載完成後自動部署補丁；若中途報錯或取消則自動中斷"""
        from managers import onlinefix_manager
        appid_str = str(appid).strip()

        def _on_complete(aid, gname, gdir):
            try:
                # 下載完成！直接執行線上補丁部署與原檔備份
                res = self.auto_install_cloud_patch_if_available(aid, gname)
                msg = res.get("msg", "線上補丁已自動部署完成！")
                if self._window:
                    js = f"if(window.onSteamDeployFinished) window.onSteamDeployFinished('{aid}', '{gname}', true, '{msg}');"
                    self._window.evaluate_js(js)
            except Exception as e:
                if self._window:
                    js = f"if(window.onSteamDeployFinished) window.onSteamDeployFinished('{aid}', '{gname}', false, '自動部署補丁失敗: {e}');"
                    self._window.evaluate_js(js)

        def _on_error(aid, gname, err_reason):
            if self._window:
                js = f"if(window.onSteamDeployCancelled) window.onSteamDeployCancelled('{aid}', '{gname}', '{err_reason}');"
                self._window.evaluate_js(js)

        started = onlinefix_manager._deploy_watcher.start_watch(
            appid_str, game_name, on_complete=_on_complete, on_error=_on_error
        )
        return {"ok": True, "started": started, "is_watching": True}

    def cancel_steam_install_watcher(self, appid: str) -> Dict[str, Any]:
        """手動取消指定遊戲的 Steam 下載監控隊列"""
        from managers import onlinefix_manager
        appid_str = str(appid).strip()
        onlinefix_manager._deploy_watcher.stop_watch(appid_str)
        return {"ok": True, "msg": "已取消背景下載監控"}

    def check_cloud_patch_available(self, appid: str, game_name: str = "") -> Dict[str, Any]:
        """即時連網檢查 Google Drive 補丁庫是否收錄該遊戲補丁 (階段 1 調用)"""
        from managers import onlinefix_manager
        try:
            appid_str = str(appid).strip()
            sources = onlinefix_manager.get_patch_sources(target_app_id=appid_str, target_app_name=game_name, allow_network=True)
            src_info = sources.get(appid_str, {})
            has_patch = bool(src_info.get('cloud_rar') or src_info.get('cloud_lua') or src_info.get('local_lua'))
            return {
                "ok": True,
                "has_patch": has_patch,
                "drive_name": src_info.get('drive_name', 'Google Drive'),
                "has_rar": bool(src_info.get('cloud_rar')),
                "has_lua": bool(src_info.get('cloud_lua'))
            }
        except Exception as e:
            return {"ok": False, "has_patch": False, "msg": str(e)}

    def download_online_patch(self, appid: str, game_name: str = "") -> Dict[str, Any]:
        """自 Google Drive 下載線上補丁到本地快取目錄 (階段 3 調用)"""
        from managers import onlinefix_manager
        try:
            appid_str = str(appid).strip()
            sources = onlinefix_manager.get_patch_sources(target_app_id=appid_str, target_app_name=game_name, allow_network=True)
            src_info = sources.get(appid_str, {})
            cloud_rar = src_info.get('cloud_rar')
            if not cloud_rar:
                return {"ok": True, "has_patch": False, "msg": "無線上補丁"}
            dl_path = onlinefix_manager.download_cloud_patch(appid_str, game_name, cloud_rar)
            if dl_path and Path(dl_path).exists():
                return {"ok": True, "has_patch": True, "path": str(dl_path), "msg": "下載成功"}
            return {"ok": False, "has_patch": True, "msg": "下載失敗"}
        except Exception as e:
            return {"ok": False, "msg": str(e)}

    def auto_install_cloud_patch_if_available(self, appid: str, game_name: str = "") -> Dict[str, Any]:
        """一鍵入庫時自動檢測並連同安裝 Google Drive / ZeiGames 各格式聯機補丁 (發出連網讀取請求)"""
        from managers import onlinefix_manager
        try:
            appid_str = str(appid).strip()
            # 1. 檢索目標網盤中是否有此遊戲專用補丁 (發出讀取請求，allow_network=True)
            sources = onlinefix_manager.get_patch_sources(target_app_id=appid_str, target_app_name=game_name, allow_network=True)
            src_info = sources.get(appid_str, {})

            if not src_info or (not src_info.get('cloud_rar') and not src_info.get('cloud_lua')):
                # 🌟 自動容錯：若記憶體快取無資料，強制刷新 Google Drive 雲端索引並重試
                onlinefix_manager.fetch_cloud_cache(force=True)
                sources = onlinefix_manager.get_patch_sources(target_app_id=appid_str, target_app_name=game_name, allow_network=True, force_refresh=True)
                src_info = sources.get(appid_str, {})

            if not src_info or (not src_info.get('cloud_rar') and not src_info.get('cloud_lua')):
                return {"ok": True, "has_patch": False, "msg": "網盤無專用聯機補丁"}

            drive_name = src_info.get('drive_name', '網盤')

            # 2. 若有雲端 Lua 清單補丁，優先安裝
            if src_info.get('cloud_lua'):
                lua_dir = self._config.get("lua_dir") or (Path(self._steam_path or "") / "config" / "lua")
                if lua_dir:
                    onlinefix_manager.install_lua(appid_str, src_info, lua_dir)

            # 3. 處理各類壓縮補丁包 (.rar / .zip / .7z 等，自動適配 online-fix.me 與 zeigames.com 解壓密碼)
            cloud_rar = src_info.get('cloud_rar')
            if cloud_rar:
                # 下載或讀取快取
                dl_path = onlinefix_manager.download_cloud_patch(appid_str, game_name, cloud_rar)
                if not dl_path:
                    return {"ok": False, "has_patch": True, "msg": f"下載 {drive_name} 聯機補丁失敗"}

                # 檢查 Steam 遊戲目錄
                game_dir = onlinefix_manager._find_steam_game_dir(appid_str)
                if game_dir and Path(game_dir).exists():
                    # 遊戲已安裝，直接解壓安裝補丁並備份原檔
                    success, msg = onlinefix_manager.install_fix(
                        appid_str, dl_path, game_dir, delete_archive=True, source_drive=drive_name
                    )
                    if success:
                        return {
                            "ok": True,
                            "has_patch": True,
                            "installed": True,
                            "drive_name": drive_name,
                            "msg": f"已成功連同安裝 {drive_name} 的 Online-Fix / ZeiGames 聯機補丁！"
                        }
                    else:
                        return {"ok": False, "has_patch": True, "installed": False, "msg": f"補丁解壓安裝失敗: {msg}"}
                else:
                    # 遊戲目錄尚未下載，補丁保留在本地快取，記錄 pending 標記
                    return {
                        "ok": True,
                        "has_patch": True,
                        "installed": False,
                        "pending": True,
                        "drive_name": drive_name,
                        "msg": f"已自 {drive_name} 備妥聯機補丁，待 Steam 下載遊戲後即可生效！"
                    }

            return {"ok": True, "has_patch": True, "drive_name": drive_name, "msg": "已部署網盤聯機配置"}
        except Exception as e:
            return {"ok": False, "msg": f"連同安裝補丁過程出錯: {e}"}

    def uninstall_online_patch(self, appid: str) -> Dict[str, Any]:
        """移除指定遊戲的線上補丁並自動還原原始備份檔案 (.bak)"""
        from managers import onlinefix_manager
        try:
            appid_str = str(appid).strip()
            success, msg = onlinefix_manager.uninstall_fix(appid_str)
            # 同步清理可能的專用 Lua 補丁
            lua_dir = self._config.get("lua_dir") or (Path(self._steam_path or "") / "config" / "lua")
            if lua_dir:
                try:
                    onlinefix_manager.uninstall_lua(appid_str, lua_dir)
                except Exception:
                    pass
            return {
                "ok": success,
                "msg": msg or ("已成功移除線上補丁並還原原始檔案！" if success else "移除線上補丁失敗")
            }
        except Exception as e:
            return {"ok": False, "msg": f"移除線上補丁出錯: {e}"}

    def install_online_patch(self, appid: str, game_name: str = "") -> Dict[str, Any]:
        """手動為指定遊戲下載安裝線上補丁 (自動將原檔備份為 .bak)"""
        return self.auto_install_cloud_patch_if_available(appid, game_name)

    def list_onlinefix_games(self) -> Dict[str, Any]:
        """掃描支援 OnlineFix 的遊戲與 Spacewar 狀態"""
        sp = self._steam_path or steam_manager.find_steam_path()
        spacewar_installed = False
        if sp:
            sw_acf = Path(sp) / "steamapps" / "appmanifest_480.acf"
            spacewar_installed = sw_acf.exists()

        return {
            "ok": True,
            "spacewar": spacewar_installed,
            "items": []
        }

    def onlinefix_launch(self, appid: str) -> Dict[str, Any]:
        """帶 -480 參數啟動遊戲"""
        try:
            os.startfile(f"steam://run/{appid}//-480")
            return {"ok": True, "message": "已成功透過 -480 協定呼叫 Steam 啟動遊戲！"}
        except Exception as e:
            return {"ok": False, "message": str(e)}

    def check_game_installed_status(self, appid: str) -> Dict[str, Any]:
        """
        精準檢查 Steam 遊戲主程式是否已完全下載安裝 (StateFlags == 4 或主執行檔就緒)
        """
        from managers import onlinefix_manager, steam_manager
        appid = str(appid).strip()
        game_dir = onlinefix_manager._find_steam_game_dir(appid)
        is_installed = False
        is_downloading = False
        state_flags = 0

        libs = set()
        if self._steam_path:
            libs.add(str(self._steam_path))
        try:
            import winreg
            key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r'Software\Valve\Steam')
            path, _ = winreg.QueryValueEx(key, 'SteamPath')
            winreg.CloseKey(key)
            libs.add(os.path.normpath(path))
        except Exception:
            pass

        for lib in list(libs):
            vdf_path = os.path.join(lib, 'steamapps', 'libraryfolders.vdf')
            if os.path.exists(vdf_path):
                try:
                    with open(vdf_path, 'r', encoding='utf-8', errors='ignore') as f:
                        for m in re.finditer(r'"path"\s*"([^"]+)"', f.read()):
                            libs.add(os.path.normpath(m.group(1).replace('\\\\', '\\')))
                except Exception:
                    pass

        for lib in libs:
            p = Path(lib) / "steamapps" / f"appmanifest_{appid}.acf"
            if p.exists():
                try:
                    content = p.read_text(encoding="utf-8", errors="ignore")
                    m = re.search(r'"StateFlags"\s*"(\d+)"', content)
                    if m:
                        state_flags = int(m.group(1))
                        if (state_flags & 4) == 4:
                            is_installed = True
                            break
                        elif (state_flags & 1024) == 1024 or (state_flags & 512) == 512 or (state_flags & 2) == 2 or (state_flags & 16) == 16:
                            is_downloading = True
                except Exception:
                    pass

        if not is_installed and game_dir and Path(game_dir).exists():
            try:
                exe_files = list(Path(game_dir).glob("*.exe"))
                if exe_files and len(exe_files) > 0:
                    is_installed = True
            except Exception:
                pass

        return {
            "ok": True,
            "appid": appid,
            "is_installed": is_installed,
            "is_downloading": is_downloading,
            "state_flags": state_flags,
            "game_dir": str(game_dir) if game_dir else ""
        }

